import comp from "C:/Users/ccica/school/forditas/src/.vuepress/.temp/pages/demo/11-fejezet.html.vue"
const data = JSON.parse("{\"path\":\"/demo/11-fejezet.html\",\"title\":\"11. fejezet\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"11. fejezet\",\"icon\":null,\"feed\":false,\"seo\":false},\"headers\":[{\"level\":2,\"title\":\"Webes űrlapok alapjai\",\"slug\":\"webes-urlapok-alapjai\",\"link\":\"#webes-urlapok-alapjai\",\"children\":[{\"level\":3,\"title\":\"Ismerd meg az elemeket, amelyeket használhatsz webes űrlapokban\",\"slug\":\"ismerd-meg-az-elemeket-amelyeket-hasznalhatsz-webes-urlapokban\",\"link\":\"#ismerd-meg-az-elemeket-amelyeket-hasznalhatsz-webes-urlapokban\",\"children\":[]}]},{\"level\":2,\"title\":\"Formanyomtatvány létrehozása\",\"slug\":\"formanyomtatvany-letrehozasa\",\"link\":\"#formanyomtatvany-letrehozasa\",\"children\":[{\"level\":3,\"title\":\"Formanyomtatvány létrehozása:\",\"slug\":\"formanyomtatvany-letrehozasa-1\",\"link\":\"#formanyomtatvany-letrehozasa-1\",\"children\":[]}]},{\"level\":2,\"title\":\"Szövegbeviteli vezérlők hozzáadása egy űrlaphoz\",\"slug\":\"szovegbeviteli-vezerlok-hozzaadasa-egy-urlaphoz\",\"link\":\"#szovegbeviteli-vezerlok-hozzaadasa-egy-urlaphoz\",\"children\":[]},{\"level\":2,\"title\":\"Rádiógombok hozzáadása egy űrlaphoz\",\"slug\":\"radiogombok-hozzaadasa-egy-urlaphoz\",\"link\":\"#radiogombok-hozzaadasa-egy-urlaphoz\",\"children\":[{\"level\":3,\"title\":\"Rádiógombok hozzáadása egy űrlaphoz\",\"slug\":\"radiogombok-hozzaadasa-egy-urlaphoz-1\",\"link\":\"#radiogombok-hozzaadasa-egy-urlaphoz-1\",\"children\":[]}]},{\"level\":2,\"title\":\"Jelölőnégyzetek hozzáadása egy űrlaphoz\",\"slug\":\"jelolonegyzetek-hozzaadasa-egy-urlaphoz\",\"link\":\"#jelolonegyzetek-hozzaadasa-egy-urlaphoz\",\"children\":[{\"level\":3,\"title\":\"Jelölőnégyzetek hozzáadása egy űrlaphoz\",\"slug\":\"jelolonegyzetek-hozzaadasa-egy-urlaphoz-1\",\"link\":\"#jelolonegyzetek-hozzaadasa-egy-urlaphoz-1\",\"children\":[]}]},{\"level\":2,\"title\":\"Legördülő lista lehetőségek hozzáadása egy űrlaphoz\",\"slug\":\"legordulo-lista-lehetosegek-hozzaadasa-egy-urlaphoz\",\"link\":\"#legordulo-lista-lehetosegek-hozzaadasa-egy-urlaphoz\",\"children\":[{\"level\":3,\"title\":\"Legördülő lista lehetőségek hozzáadása egy űrlaphoz\",\"slug\":\"legordulo-lista-lehetosegek-hozzaadasa-egy-urlaphoz-1\",\"link\":\"#legordulo-lista-lehetosegek-hozzaadasa-egy-urlaphoz-1\",\"children\":[]}]},{\"level\":2,\"title\":\"A Visual Studio Code beszúrja a select elemet:\",\"slug\":\"a-visual-studio-code-beszurja-a-select-elemet\",\"link\":\"#a-visual-studio-code-beszurja-a-select-elemet\",\"children\":[]},{\"level\":2,\"title\":\"Parancsgombok hozzáadása űrlaphoz\",\"slug\":\"parancsgombok-hozzaadasa-urlaphoz\",\"link\":\"#parancsgombok-hozzaadasa-urlaphoz\",\"children\":[{\"level\":3,\"title\":\"Parancsgombok hozzáadása űrlaphoz\",\"slug\":\"parancsgombok-hozzaadasa-urlaphoz-1\",\"link\":\"#parancsgombok-hozzaadasa-urlaphoz-1\",\"children\":[]}]}],\"readingTime\":{\"minutes\":12.34,\"words\":3703},\"filePathRelative\":\"demo/11-fejezet.md\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
