import comp from "D:/programozas/vuepress/forditas/src/.vuepress/.temp/pages/demo/3-fejezet.html.vue"
const data = JSON.parse("{\"path\":\"/demo/3-fejezet.html\",\"title\":\"3. fejezet\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"3. fejezet\",\"icon\":null,\"feed\":false,\"seo\":false},\"headers\":[{\"level\":2,\"title\":\"Ismerje meg a weboldalak strukturálásának elemeit\",\"slug\":\"ismerje-meg-a-weboldalak-strukturalasanak-elemeit\",\"link\":\"#ismerje-meg-a-weboldalak-strukturalasanak-elemeit\",\"children\":[{\"level\":3,\"title\":\"Szemantikus és nem szemantikus elemek megragadása\",\"slug\":\"szemantikus-es-nem-szemantikus-elemek-megragadasa\",\"link\":\"#szemantikus-es-nem-szemantikus-elemek-megragadasa\",\"children\":[]}]},{\"level\":2,\"title\":\"Elemek kiválasztása span és div elemekkel\",\"slug\":\"elemek-kivalasztasa-span-es-div-elemekkel\",\"link\":\"#elemek-kivalasztasa-span-es-div-elemekkel\",\"children\":[{\"level\":3,\"title\":\"Elemek kiválasztása span és div elemekkel\",\"slug\":\"elemek-kivalasztasa-span-es-div-elemekkel-1\",\"link\":\"#elemek-kivalasztasa-span-es-div-elemekkel-1\",\"children\":[]},{\"level\":3,\"title\":\"Szöveg kiválasztása a div elemmel\",\"slug\":\"szoveg-kivalasztasa-a-div-elemmel\",\"link\":\"#szoveg-kivalasztasa-a-div-elemmel\",\"children\":[]}]},{\"level\":2,\"title\":\"Fejlécelemek és láblécelemek létrehozása\",\"slug\":\"fejlecelemek-es-lablecelemek-letrehozasa\",\"link\":\"#fejlecelemek-es-lablecelemek-letrehozasa\",\"children\":[{\"level\":3,\"title\":\"Fejlécelemek és láblécelemek létrehozása\",\"slug\":\"fejlecelemek-es-lablecelemek-letrehozasa-1\",\"link\":\"#fejlecelemek-es-lablecelemek-letrehozasa-1\",\"children\":[]}]},{\"level\":2,\"title\":\"Cikk elemek hozzáadása az oldalhoz\",\"slug\":\"cikk-elemek-hozzaadasa-az-oldalhoz\",\"link\":\"#cikk-elemek-hozzaadasa-az-oldalhoz\",\"children\":[{\"level\":3,\"title\":\"Cikk elemek hozzáadása az oldalhoz:\",\"slug\":\"cikk-elemek-hozzaadasa-az-oldalhoz-1\",\"link\":\"#cikk-elemek-hozzaadasa-az-oldalhoz-1\",\"children\":[]}]},{\"level\":2,\"title\":\"Hozzon létre kiemelt idézeteket az aside elemmel\",\"slug\":\"hozzon-letre-kiemelt-idezeteket-az-aside-elemmel\",\"link\":\"#hozzon-letre-kiemelt-idezeteket-az-aside-elemmel\",\"children\":[{\"level\":3,\"title\":\"Készítsen kiemelt idézeteket az aside elemmel:\",\"slug\":\"keszitsen-kiemelt-idezeteket-az-aside-elemmel\",\"link\":\"#keszitsen-kiemelt-idezeteket-az-aside-elemmel\",\"children\":[]}]},{\"level\":2,\"title\":\"Oldal felosztása az Elemek szakasz használatával\",\"slug\":\"oldal-felosztasa-az-elemek-szakasz-hasznalataval\",\"link\":\"#oldal-felosztasa-az-elemek-szakasz-hasznalataval\",\"children\":[]},{\"level\":2,\"title\":\"Összecsukható szakaszok létrehozása\",\"slug\":\"osszecsukhato-szakaszok-letrehozasa\",\"link\":\"#osszecsukhato-szakaszok-letrehozasa\",\"children\":[]}],\"readingTime\":{\"minutes\":10.42,\"words\":3127},\"filePathRelative\":\"demo/3-fejezet.md\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
