import comp from "C:/Users/d3asyn/stuff/School/forditas/src/.vuepress/.temp/pages/demo/4-fejezet.html.vue"
const data = JSON.parse("{\"path\":\"/demo/4-fejezet.html\",\"title\":\"4. fejezet\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"4. fejezet\",\"icon\":null,\"feed\":false,\"seo\":false},\"headers\":[{\"level\":2,\"title\":\"Ragadd meg az alapokat webes képformátumok terén.\",\"slug\":\"ragadd-meg-az-alapokat-webes-kepformatumok-teren\",\"link\":\"#ragadd-meg-az-alapokat-webes-kepformatumok-teren\",\"children\":[{\"level\":3,\"title\":\"Annak megértése hogy, miért fontos a képfájl mérete\",\"slug\":\"annak-megertese-hogy-miert-fontos-a-kepfajl-merete\",\"link\":\"#annak-megertese-hogy-miert-fontos-a-kepfajl-merete\",\"children\":[]},{\"level\":3,\"title\":\"Azok a tényezők, amelyek befolyásolják a képfájl méretét:\",\"slug\":\"azok-a-tenyezok-amelyek-befolyasoljak-a-kepfajl-meretet\",\"link\":\"#azok-a-tenyezok-amelyek-befolyasoljak-a-kepfajl-meretet\",\"children\":[]},{\"level\":3,\"title\":\"A legelterjedtebben használt webes képformátumok megértése\",\"slug\":\"a-legelterjedtebben-hasznalt-webes-kepformatumok-megertese\",\"link\":\"#a-legelterjedtebben-hasznalt-webes-kepformatumok-megertese\",\"children\":[]}]},{\"level\":2,\"title\":\"Indítsd el a GIMP-et és hajtsd végre az alapvető lépéseket.\",\"slug\":\"inditsd-el-a-gimp-et-es-hajtsd-vegre-az-alapveto-lepeseket\",\"link\":\"#inditsd-el-a-gimp-et-es-hajtsd-vegre-az-alapveto-lepeseket\",\"children\":[{\"level\":3,\"title\":\"Indítsd el a GIMP-et és nyiss meg egy képfájlt.\",\"slug\":\"inditsd-el-a-gimp-et-es-nyiss-meg-egy-kepfajlt\",\"link\":\"#inditsd-el-a-gimp-et-es-nyiss-meg-egy-kepfajlt\",\"children\":[]}]},{\"level\":2,\"title\":\"Folytatva a GIMP indításához és alapvető lépések végrehajtásához szükséges lépéseket:\",\"slug\":\"folytatva-a-gimp-inditasahoz-es-alapveto-lepesek-vegrehajtasahoz-szukseges-lepeseket\",\"link\":\"#folytatva-a-gimp-inditasahoz-es-alapveto-lepesek-vegrehajtasahoz-szukseges-lepeseket\",\"children\":[{\"level\":3,\"title\":\"Közelítés vagy távolítás a képfájlon\",\"slug\":\"kozelites-vagy-tavolitas-a-kepfajlon\",\"link\":\"#kozelites-vagy-tavolitas-a-kepfajlon\",\"children\":[]},{\"level\":3,\"title\":\"Változások mentése egy képfájlba és annak bezárása.\",\"slug\":\"valtozasok-mentese-egy-kepfajlba-es-annak-bezarasa\",\"link\":\"#valtozasok-mentese-egy-kepfajlba-es-annak-bezarasa\",\"children\":[]}]},{\"level\":2,\"title\":\"Kép elforgatása vagy kiegyenesítése\",\"slug\":\"kep-elforgatasa-vagy-kiegyenesitese\",\"link\":\"#kep-elforgatasa-vagy-kiegyenesitese\",\"children\":[]},{\"level\":2,\"title\":\"Kép kivágása\",\"slug\":\"kep-kivagasa\",\"link\":\"#kep-kivagasa\",\"children\":[]},{\"level\":2,\"title\":\"Kép átméretezése\",\"slug\":\"kep-atmeretezese\",\"link\":\"#kep-atmeretezese\",\"children\":[]},{\"level\":2,\"title\":\"Színek számának csökkentése\",\"slug\":\"szinek-szamanak-csokkentese\",\"link\":\"#szinek-szamanak-csokkentese\",\"children\":[]}],\"readingTime\":{\"minutes\":10.77,\"words\":3231},\"filePathRelative\":\"demo/4-fejezet.md\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
